### PR TITLE
Add SASL SCRAM support

### PR DESCRIPTION
**Pull request by worms**
I have tested both SCRAM-SHA-256 and SCRAM-SHA-512. However, SCRAM-SHA-512 requires an upstream change to the scram library. Therefore I have commented out the SHA-512 code.

### CODE REVIEW

**Comment by everesio** [comment]
Thank you for your contribution! 
I need some time to setup the test environment and perform the review.

**Comment by everesio** [comment]
Without deep dive into code (I will do it later), I successfully tested SCRAM-SHA-256.

Let's wait for your https://github.com/xdg-go/scram/pull/1 to be merged to have complete implementation with SCRAM-SHA-512. After that PR is merged, the library should be vendored.

**Comment by worms** [comment]
Sounds good. I haven't heard anything from them yet :(
I will give them a few more days. If by Wednesday I don't hear from them I will come up with another solution that doesn't rely on their type.

**Comment by worms** [comment]
Looks like the xdg-go guys are not around. I will make the change not reliant on that upstreamed change and upload at some point this week

**Pull request merged**
